// vite.config.js
// WorkLedger — Production Vite Configuration
// Updated: PWA + iOS/Android installability (Session 19)
// ⚠️  Service workers ONLY run after: npm run build && npm run preview
//     Never test PWA/SW in npm run dev — it will NOT work.

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),

    VitePWA({
      // Auto-update the service worker when a new build is deployed.
      registerType: 'autoUpdate',

      // Inject SW registration script automatically into the built HTML.
      injectRegister: 'auto',

      // Precache: static assets generated by pwa-asset-generator.
      // pwa-asset-generator puts all files directly in /public root
      // (not in a subfolder) — so patterns match root-level filenames.
      includeAssets: [
        'favicon.ico',
        'robots.txt',
        'apple-icon-180.png',
        'apple-splash-*.png',
        'manifest-icon-192.png',
        'manifest-icon-512.png',
      ],

      // Service workers break Vite HMR in dev mode.
      // Always test PWA with: npm run build && npm run preview
      devOptions: {
        enabled: false,
      },

      // ── Web App Manifest ───────────────────────────────────────────────
      // IMPORTANT: This config generates the manifest that Vite serves.
      // Only reference icon files that actually exist in /public.
      // After running pwa-asset-generator, the only icon files generated are:
      //   /public/manifest-icon-192.png
      //   /public/manifest-icon-512.png
      //   /public/apple-icon-180.png
      // The old icon-72.png, icon-96.png etc. were NOT generated — do not
      // reference them here or the browser will log failed-to-load errors.
      manifest: {
        name: 'WorkLedger',
        short_name: 'WorkLedger',
        description: 'Contract-aware work reporting for field technicians',
        start_url: '/',
        id: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait-primary',
        background_color: '#0f172a',
        theme_color: '#0f172a',
        lang: 'en-MY',
        categories: ['business', 'productivity', 'utilities'],

        icons: [
          {
            // 192px — required minimum for Android install prompt
            src: '/manifest-icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            // 512px any — required for splash screen on Android
            src: '/manifest-icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            // 512px maskable — adaptive icon (rounded/squircle on Android).
            // We reuse the same file; it works fine without the extra padding
            // as a fallback. Generate a proper maskable version later if needed.
            src: '/manifest-icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],

        // Long-press shortcuts on Android launcher icon
        shortcuts: [
          {
            name: 'New Work Entry',
            short_name: 'New Entry',
            description: 'Create a new work entry',
            url: '/work/new',
            icons: [{ src: '/manifest-icon-192.png', sizes: '192x192' }],
          },
          {
            name: 'Pending Approvals',
            short_name: 'Approvals',
            description: 'Review work entries awaiting approval',
            url: '/work/approvals',
            icons: [{ src: '/manifest-icon-192.png', sizes: '192x192' }],
          },
        ],
      },

      // ── Workbox Service Worker Strategy ───────────────────────────────
      workbox: {
        // SPA fallback: all navigation requests serve index.html
        navigateFallback: '/index.html',

        // Do NOT serve index.html for API/auth/storage calls
        navigateFallbackDenylist: [
          /^\/api/,
          /^\/rest/,
          /^\/auth/,
          /^\/storage/,
        ],

        // Precache all build output assets
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],

        // Skip files larger than 3MB from precache
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,

        runtimeCaching: [
          // ── Supabase REST API — NetworkFirst ──────────────────────────
          {
            urlPattern: /^https:\/\/[^/]+\.supabase\.co\/rest\/v1\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'supabase-api-cache',
              networkTimeoutSeconds: 10,
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 24 * 60 * 60,
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // ── Supabase Auth — NetworkOnly ───────────────────────────────
          {
            urlPattern: /^https:\/\/[^/]+\.supabase\.co\/auth\/.*/i,
            handler: 'NetworkOnly',
          },

          // ── Supabase Storage — CacheFirst ─────────────────────────────
          {
            urlPattern: /^https:\/\/[^/]+\.supabase\.co\/storage\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'supabase-storage-cache',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 7 * 24 * 60 * 60,
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // ── Google Fonts ──────────────────────────────────────────────
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: { cacheName: 'google-fonts-stylesheets' },
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: {
                maxEntries: 30,
                maxAgeSeconds: 365 * 24 * 60 * 60,
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],

  // ── Build Optimisation ─────────────────────────────────────────────────
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-offline': ['dexie'],
          'vendor-auth': ['@supabase/supabase-js'],
          'vendor-pdf': ['jspdf', 'jspdf-autotable'],
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
        },
      },
    },
  },
})
