-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  actor_user_id uuid,
  actor_org_id uuid,
  target_org_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id),
  CONSTRAINT activity_logs_actor_org_id_fkey FOREIGN KEY (actor_org_id) REFERENCES public.organizations(id),
  CONSTRAINT activity_logs_target_org_id_fkey FOREIGN KEY (target_org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_entry_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['photo'::text, 'signature'::text, 'document'::text])),
  file_size integer,
  mime_type text NOT NULL CHECK (mime_type = ANY (ARRAY['image/jpeg'::text, 'image/jpg'::text, 'image/png'::text, 'image/webp'::text, 'image/gif'::text, 'application/pdf'::text, 'application/msword'::text, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'::text, 'application/vnd.ms-excel'::text, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'::text])),
  storage_bucket text DEFAULT 'workledger-attachments'::text,
  storage_path text,
  storage_url text,
  field_id text NOT NULL,
  width integer,
  height integer,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'uploaded'::text, 'failed'::text])),
  synced_at timestamp with time zone,
  sync_error text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT attachments_pkey PRIMARY KEY (id),
  CONSTRAINT attachments_work_entry_id_fkey FOREIGN KEY (work_entry_id) REFERENCES public.work_entries(id),
  CONSTRAINT attachments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT attachments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.contract_layouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  layout_id uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  notes text,
  CONSTRAINT contract_layouts_pkey PRIMARY KEY (id),
  CONSTRAINT contract_layouts_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_layouts_layout_id_fkey FOREIGN KEY (layout_id) REFERENCES public.report_layouts(id),
  CONSTRAINT contract_layouts_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  template_id uuid NOT NULL,
  label text,
  sort_order integer NOT NULL DEFAULT 0,
  is_default boolean NOT NULL DEFAULT false,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_templates_pkey PRIMARY KEY (id),
  CONSTRAINT contract_templates_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_templates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT contract_templates_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  contract_number text NOT NULL,
  contract_name text NOT NULL,
  contract_type text,
  contract_category text CHECK (contract_category = ANY (ARRAY['preventive-maintenance'::text, 'comprehensive-maintenance'::text, 'annual-maintenance'::text, 'sla-based-maintenance'::text, 'corrective-maintenance'::text, 'emergency-on-call'::text, 'time-and-material'::text, 'construction-daily-diary'::text])),
  reporting_frequency text NOT NULL DEFAULT 'daily'::text CHECK (reporting_frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text, 'quarterly'::text, 'annually'::text, 'adhoc'::text, 'per-visit'::text])),
  requires_approval boolean NOT NULL DEFAULT true,
  sla_response_time_mins integer,
  sla_resolution_time_hours integer,
  sla_tier text CHECK (sla_tier = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  maintenance_cycle text,
  asset_categories jsonb DEFAULT '[]'::jsonb,
  valid_from date NOT NULL,
  valid_until date NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'suspended'::text, 'completed'::text, 'cancelled'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  default_layout_id uuid,
  contract_value numeric,
  description text,
  organization_id uuid,
  performing_org_id uuid,
  contract_role text NOT NULL DEFAULT 'main'::text CHECK (contract_role = ANY (ARRAY['main'::text, 'sub'::text])),
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT contracts_default_layout_id_fkey FOREIGN KEY (default_layout_id) REFERENCES public.report_layouts(id),
  CONSTRAINT contracts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contracts_performing_org_id_fkey FOREIGN KEY (performing_org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.generated_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['custom'::text, 'monthly'::text, 'weekly'::text])),
  report_title text NOT NULL,
  entry_ids ARRAY NOT NULL,
  options jsonb DEFAULT '{}'::jsonb,
  period_start date,
  period_end date,
  entry_count integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text])),
  generated_by uuid,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT generated_reports_pkey PRIMARY KEY (id),
  CONSTRAINT generated_reports_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT generated_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id),
  CONSTRAINT generated_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.org_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'worker'::text CHECK (role = ANY (ARRAY['org_owner'::text, 'org_admin'::text, 'manager'::text, 'technician'::text, 'subcontractor'::text, 'worker'::text, 'client'::text])),
  invited_by uuid,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_members_pkey PRIMARY KEY (id),
  CONSTRAINT org_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT org_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  settings jsonb DEFAULT '{"branding": {"logo_url": null, "primary_color": "#3B82F6"}, "features": {"offline_sync": true, "sla_tracking": true, "photo_uploads": true, "pdf_generation": true}}'::jsonb,
  storage_quota_mb integer DEFAULT 1024,
  user_limit integer DEFAULT 10,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'basic'::text, 'professional'::text, 'enterprise'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  org_type text DEFAULT 'client'::text CHECK (org_type = ANY (ARRAY['client'::text, 'main_contractor'::text, 'subcontractor'::text, 'freelancer'::text])),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  project_name text NOT NULL,
  project_code text,
  client_name text NOT NULL,
  site_address text,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'on_hold'::text, 'cancelled'::text])),
  metadata jsonb DEFAULT '{"tags": [], "notes": "", "contacts": []}'::jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.reject_entry_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_entry_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  contract_id uuid NOT NULL,
  template_id uuid NOT NULL,
  entry_date date NOT NULL,
  entry_created_by uuid NOT NULL,
  rejected_by uuid NOT NULL,
  rejected_at timestamp with time zone NOT NULL DEFAULT now(),
  rejection_reason text NOT NULL,
  rejection_count integer NOT NULL DEFAULT 1 CHECK (rejection_count >= 1),
  entry_data_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reject_entry_history_pkey PRIMARY KEY (id),
  CONSTRAINT rej_hist_work_entry_fkey FOREIGN KEY (work_entry_id) REFERENCES public.work_entries(id),
  CONSTRAINT rej_hist_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT rej_hist_contract_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT rej_hist_template_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT rej_hist_entry_created_by_fkey FOREIGN KEY (entry_created_by) REFERENCES auth.users(id),
  CONSTRAINT rej_hist_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_layouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  layout_id text NOT NULL UNIQUE CHECK (layout_id ~ '^[a-z0-9_]+$'::text),
  layout_name text NOT NULL CHECK (length(TRIM(BOTH FROM layout_name)) > 0),
  description text,
  compatible_template_types ARRAY NOT NULL CHECK (array_length(compatible_template_types, 1) > 0),
  layout_schema jsonb NOT NULL,
  binding_rules jsonb NOT NULL,
  preview_config jsonb,
  is_public boolean DEFAULT true,
  organization_id uuid,
  version text NOT NULL DEFAULT '1.0'::text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_layouts_pkey PRIMARY KEY (id),
  CONSTRAINT report_layouts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT report_layouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.subcontractor_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  main_contractor_org_id uuid NOT NULL,
  subcontractor_org_id uuid NOT NULL,
  project_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'terminated'::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  contract_id uuid,
  CONSTRAINT subcontractor_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT subcontractor_relationships_main_org_fkey FOREIGN KEY (main_contractor_org_id) REFERENCES public.organizations(id),
  CONSTRAINT subcontractor_relationships_sub_org_fkey FOREIGN KEY (subcontractor_org_id) REFERENCES public.organizations(id),
  CONSTRAINT subcontractor_relationships_project_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT subcontractor_relationships_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT subcontractor_relationships_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id text NOT NULL UNIQUE,
  template_name text NOT NULL,
  industry text,
  contract_category text,
  report_type text,
  fields_schema jsonb NOT NULL,
  validation_rules jsonb DEFAULT '{}'::jsonb,
  pdf_layout jsonb DEFAULT '{}'::jsonb,
  version text DEFAULT '1.0'::text,
  is_locked boolean DEFAULT false,
  is_public boolean DEFAULT true,
  organization_id uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  default_layout_id text,
  CONSTRAINT templates_pkey PRIMARY KEY (id),
  CONSTRAINT templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fk_templates_default_layout FOREIGN KEY (default_layout_id) REFERENCES public.report_layouts(layout_id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  full_name text,
  phone_number text,
  avatar_url text,
  preferences jsonb DEFAULT '{"theme": "light", "language": "en", "default_view": "list", "notifications": {"push": true, "email": true}}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  global_role text CHECK (global_role = ANY (ARRAY['super_admin'::text, 'bina_jaya_staff'::text])),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.work_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  template_id uuid NOT NULL,
  entry_date date NOT NULL,
  shift text,
  data jsonb NOT NULL,
  sla_response_actual_mins integer,
  sla_resolution_actual_hours numeric,
  sla_met boolean,
  penalty_amount numeric,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  submitted_by uuid,
  approved_at timestamp with time zone,
  approved_by uuid,
  approval_remarks text,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  deleted_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT work_entries_pkey PRIMARY KEY (id),
  CONSTRAINT work_entries_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT work_entries_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT work_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT work_entries_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT work_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT work_entries_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES auth.users(id),
  CONSTRAINT work_entries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);